### ISSUE TITLE
An example or two would be nice....

### ISSUE THREAD

**Issue by CharlesIrvineKC** [tommueller/ng-mat-search-bar#23]
I've got this wired into my top level component, but now I don't quite know how to make it work. I'm probably just too much of an Angular/NgMaterial newbie still. How much work would it be be code up an example that actually searches through some data? Thanks

**Comment by tommueller** [comment]
@ChuckIrvine sorry but this is not really part of this library. There should be enough online tutorials on how to search using Angular. Just googled for 2 minutes and found this for example:

https://stackblitz.com/edit/angular-search-filter?file=app%2Fapp.component.html
https://alligator.io/angular/real-time-search-angular-rxjs/

Otherwise refer to stackoverflow or similiar pages for questions like this.

Cheers!

**Comment by CharlesIrvineKC** [comment]
No problem. I'm coming up to speed using the example code from the autocomplete documentation at the NgMaterial site. I think my confusion was thinking that ng-mat-search-bar, based on its name, included some built in search functionality. I see now that it doesn't.

**Comment by tommueller** [comment]
Ah alright. No it's just a Material Design styled search-input that can be connected to any search functionality you can think of ;)
